[package]
name = "rust-ledger"
version = "0.1.0"
edition = "2024"

[workspace]
members = [
    "domain",
    "application",
    "infrastructure", "presentation",
]

[dependencies]
domain = { path = "domain" }
application = { path = "application" }
infrastructure = { path = "infrastructure" }
presentation = { path = "presentation" }

serde = "1.0.228"
serde_json = "1.0.150"
tokio = { version = "1.52.3", features = ["full"] }
uuid = { version = "1.23.4", features = ["v7"] }
dotenvy = "0.15.7"
