[package]
name = "infrastructure"
version = "0.1.0"
edition = "2024"

[dependencies]
domain = { path = "../domain" }
application = { path = "../application" }
async-trait = "0.1.89"
serde_json = "1.0.150"
rocksdb = "0.24.0"
uuid = { version = "1.23.4", features = ["v7"] }
dashmap = "6.2.1"
tokio = { version = "1.52.3", features = ["sync"] }
tracing = "0.1.44"
